abstract: For When Template Systems Are Too Huge And Heredocs Too Messy
author: Sebastian Riedel, C<sri@oook.de>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: HTML-Simple
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTML::Entities: 0
  perl: 5.8.1
version: 1.0
